//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZURIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdAgent { get; set; }
        public int IdTovar { get; set; }
    
        public virtual AgentSet AgentSet { get; set; }
        public virtual ClientSet ClientSet { get; set; }
        public virtual TovarSet TovarSet { get; set; }
    }
}
